let score: number[] = []
let freqs: number[] = []
input.onButtonPressed(Button.A, function () {
    basic.showNumber(3)
    basic.pause(250)
    basic.showNumber(2)
    basic.pause(250)
    basic.showNumber(1)
    basic.pause(250)
    basic.showLeds(`
        . . . . .
        . . . . .
        . . . . .
        . . . . .
        . . . . .
        `)
    pins.digitalWritePin(DigitalPin.P1, 0)
    servos.P2.setAngle(90)
    basic.pause(150)
    pins.digitalWritePin(DigitalPin.P1, 1)
    music.ringTone(330)
    basic.pause(260)
    music.rest(10)
    pins.digitalWritePin(DigitalPin.P1, 0)
    servos.P2.setAngle(90)
    basic.pause(150)
    pins.digitalWritePin(DigitalPin.P1, 1)
    music.ringTone(330)
    basic.pause(260)
    music.rest(10)
    pins.digitalWritePin(DigitalPin.P1, 0)
    servos.P2.setAngle(96)
    basic.pause(150)
    pins.digitalWritePin(DigitalPin.P1, 1)
    music.ringTone(350)
    basic.pause(260)
    music.rest(10)
    pins.digitalWritePin(DigitalPin.P1, 0)
    servos.P2.setAngle(102)
    basic.pause(150)
    pins.digitalWritePin(DigitalPin.P1, 1)
    music.ringTone(392)
    basic.pause(260)
    music.rest(10)
    pins.digitalWritePin(DigitalPin.P1, 0)
    servos.P2.setAngle(102)
    basic.pause(150)
    pins.digitalWritePin(DigitalPin.P1, 1)
    music.ringTone(392)
    basic.pause(260)
    music.rest(10)
    pins.digitalWritePin(DigitalPin.P1, 0)
    servos.P2.setAngle(96)
    basic.pause(150)
    pins.digitalWritePin(DigitalPin.P1, 1)
    music.ringTone(350)
    basic.pause(260)
    music.rest(10)
    pins.digitalWritePin(DigitalPin.P1, 0)
    servos.P2.setAngle(90)
    basic.pause(150)
    pins.digitalWritePin(DigitalPin.P1, 1)
    music.ringTone(330)
    basic.pause(260)
    music.rest(10)
    pins.digitalWritePin(DigitalPin.P1, 0)
    servos.P2.setAngle(84)
    basic.pause(150)
    pins.digitalWritePin(DigitalPin.P1, 1)
    music.ringTone(294)
    basic.pause(260)
    music.rest(10)
    pins.digitalWritePin(DigitalPin.P1, 0)
    servos.P2.setAngle(78)
    basic.pause(150)
    pins.digitalWritePin(DigitalPin.P1, 1)
    music.ringTone(262)
    basic.pause(260)
    music.rest(10)
    pins.digitalWritePin(DigitalPin.P1, 0)
    servos.P2.setAngle(78)
    basic.pause(150)
    pins.digitalWritePin(DigitalPin.P1, 1)
    music.ringTone(262)
    basic.pause(260)
    music.rest(10)
    pins.digitalWritePin(DigitalPin.P1, 0)
    servos.P2.setAngle(84)
    basic.pause(150)
    pins.digitalWritePin(DigitalPin.P1, 1)
    music.ringTone(294)
    basic.pause(260)
    music.rest(10)
    pins.digitalWritePin(DigitalPin.P1, 0)
    servos.P2.setAngle(90)
    basic.pause(150)
    pins.digitalWritePin(DigitalPin.P1, 1)
    music.ringTone(330)
    basic.pause(260)
    music.rest(10)
    pins.digitalWritePin(DigitalPin.P1, 0)
    servos.P2.setAngle(90)
    basic.pause(150)
    pins.digitalWritePin(DigitalPin.P1, 1)
    music.ringTone(330)
    basic.pause(460)
    music.rest(10)
    pins.digitalWritePin(DigitalPin.P1, 0)
    servos.P2.setAngle(84)
    basic.pause(150)
    pins.digitalWritePin(DigitalPin.P1, 1)
    music.ringTone(294)
    basic.pause(60)
    music.rest(10)
    pins.digitalWritePin(DigitalPin.P1, 0)
    servos.P2.setAngle(84)
    basic.pause(150)
    pins.digitalWritePin(DigitalPin.P1, 1)
    music.ringTone(294)
    basic.pause(260)
    music.rest(10)
    pins.digitalWritePin(DigitalPin.P1, 0)
    basic.pause(390)
    music.rest(10)
    servos.P2.setAngle(90)
    basic.pause(150)
    pins.digitalWritePin(DigitalPin.P1, 1)
    music.ringTone(330)
    basic.pause(260)
    music.rest(10)
    pins.digitalWritePin(DigitalPin.P1, 0)
    servos.P2.setAngle(90)
    basic.pause(150)
    pins.digitalWritePin(DigitalPin.P1, 1)
    music.ringTone(330)
    basic.pause(260)
    music.rest(10)
    pins.digitalWritePin(DigitalPin.P1, 0)
    servos.P2.setAngle(96)
    basic.pause(150)
    pins.digitalWritePin(DigitalPin.P1, 1)
    music.ringTone(350)
    basic.pause(260)
    music.rest(10)
    pins.digitalWritePin(DigitalPin.P1, 0)
    servos.P2.setAngle(102)
    basic.pause(150)
    pins.digitalWritePin(DigitalPin.P1, 1)
    music.ringTone(392)
    basic.pause(260)
    music.rest(10)
    pins.digitalWritePin(DigitalPin.P1, 0)
    servos.P2.setAngle(102)
    basic.pause(150)
    pins.digitalWritePin(DigitalPin.P1, 1)
    music.ringTone(392)
    basic.pause(260)
    music.rest(10)
    pins.digitalWritePin(DigitalPin.P1, 0)
    servos.P2.setAngle(96)
    basic.pause(150)
    pins.digitalWritePin(DigitalPin.P1, 1)
    music.ringTone(350)
    basic.pause(260)
    music.rest(10)
    pins.digitalWritePin(DigitalPin.P1, 0)
    servos.P2.setAngle(90)
    basic.pause(150)
    pins.digitalWritePin(DigitalPin.P1, 1)
    music.ringTone(330)
    basic.pause(260)
    music.rest(10)
    pins.digitalWritePin(DigitalPin.P1, 0)
    servos.P2.setAngle(84)
    basic.pause(150)
    pins.digitalWritePin(DigitalPin.P1, 1)
    music.ringTone(294)
    basic.pause(260)
    music.rest(10)
    pins.digitalWritePin(DigitalPin.P1, 0)
    servos.P2.setAngle(78)
    basic.pause(150)
    pins.digitalWritePin(DigitalPin.P1, 1)
    music.ringTone(262)
    basic.pause(260)
    music.rest(10)
    pins.digitalWritePin(DigitalPin.P1, 0)
    servos.P2.setAngle(78)
    basic.pause(150)
    pins.digitalWritePin(DigitalPin.P1, 1)
    music.ringTone(262)
    basic.pause(260)
    music.rest(10)
    pins.digitalWritePin(DigitalPin.P1, 0)
    servos.P2.setAngle(84)
    basic.pause(150)
    pins.digitalWritePin(DigitalPin.P1, 1)
    music.ringTone(294)
    basic.pause(260)
    music.rest(10)
    pins.digitalWritePin(DigitalPin.P1, 0)
    servos.P2.setAngle(90)
    basic.pause(150)
    pins.digitalWritePin(DigitalPin.P1, 1)
    music.ringTone(330)
    basic.pause(260)
    music.rest(10)
    pins.digitalWritePin(DigitalPin.P1, 0)
    servos.P2.setAngle(84)
    basic.pause(150)
    pins.digitalWritePin(DigitalPin.P1, 1)
    music.ringTone(294)
    basic.pause(460)
    music.rest(10)
    pins.digitalWritePin(DigitalPin.P1, 0)
    servos.P2.setAngle(78)
    basic.pause(150)
    pins.digitalWritePin(DigitalPin.P1, 1)
    music.ringTone(262)
    basic.pause(60)
    music.rest(10)
    pins.digitalWritePin(DigitalPin.P1, 0)
    servos.P2.setAngle(78)
    basic.pause(150)
    pins.digitalWritePin(DigitalPin.P1, 1)
    music.ringTone(262)
    basic.pause(260)
    music.rest(10)
    pins.digitalWritePin(DigitalPin.P1, 0)
    basic.pause(390)
    music.rest(10)
    servos.P2.setAngle(84)
    basic.pause(150)
    pins.digitalWritePin(DigitalPin.P1, 1)
    music.ringTone(294)
    basic.pause(260)
    music.rest(10)
    pins.digitalWritePin(DigitalPin.P1, 0)
    servos.P2.setAngle(84)
    basic.pause(150)
    pins.digitalWritePin(DigitalPin.P1, 1)
    music.ringTone(294)
    basic.pause(260)
    music.rest(10)
    pins.digitalWritePin(DigitalPin.P1, 0)
    servos.P2.setAngle(90)
    basic.pause(150)
    pins.digitalWritePin(DigitalPin.P1, 1)
    music.ringTone(330)
    basic.pause(260)
    music.rest(10)
    pins.digitalWritePin(DigitalPin.P1, 0)
    servos.P2.setAngle(78)
    basic.pause(150)
    pins.digitalWritePin(DigitalPin.P1, 1)
    music.ringTone(262)
    basic.pause(260)
    music.rest(10)
    pins.digitalWritePin(DigitalPin.P1, 0)
    servos.P2.setAngle(84)
    basic.pause(150)
    pins.digitalWritePin(DigitalPin.P1, 1)
    music.ringTone(294)
    basic.pause(260)
    music.rest(10)
    pins.digitalWritePin(DigitalPin.P1, 0)
    servos.P2.setAngle(90)
    basic.pause(150)
    pins.digitalWritePin(DigitalPin.P1, 1)
    music.ringTone(330)
    basic.pause(60)
    music.rest(10)
    pins.digitalWritePin(DigitalPin.P1, 0)
    servos.P2.setAngle(96)
    basic.pause(150)
    pins.digitalWritePin(DigitalPin.P1, 1)
    music.ringTone(350)
    basic.pause(60)
    music.rest(10)
    pins.digitalWritePin(DigitalPin.P1, 0)
    servos.P2.setAngle(90)
    basic.pause(150)
    pins.digitalWritePin(DigitalPin.P1, 1)
    music.ringTone(330)
    basic.pause(260)
    music.rest(10)
    pins.digitalWritePin(DigitalPin.P1, 0)
    servos.P2.setAngle(78)
    basic.pause(150)
    pins.digitalWritePin(DigitalPin.P1, 1)
    music.ringTone(262)
    basic.pause(260)
    music.rest(10)
    pins.digitalWritePin(DigitalPin.P1, 0)
    servos.P2.setAngle(84)
    basic.pause(150)
    pins.digitalWritePin(DigitalPin.P1, 1)
    music.ringTone(294)
    basic.pause(260)
    music.rest(10)
    pins.digitalWritePin(DigitalPin.P1, 0)
    servos.P2.setAngle(90)
    basic.pause(150)
    pins.digitalWritePin(DigitalPin.P1, 1)
    music.ringTone(330)
    basic.pause(60)
    music.rest(10)
    pins.digitalWritePin(DigitalPin.P1, 0)
    servos.P2.setAngle(96)
    basic.pause(150)
    pins.digitalWritePin(DigitalPin.P1, 1)
    music.ringTone(350)
    basic.pause(60)
    music.rest(10)
    pins.digitalWritePin(DigitalPin.P1, 0)
    servos.P2.setAngle(90)
    basic.pause(150)
    pins.digitalWritePin(DigitalPin.P1, 1)
    music.ringTone(330)
    basic.pause(260)
    music.rest(10)
    pins.digitalWritePin(DigitalPin.P1, 0)
    servos.P2.setAngle(78)
    basic.pause(150)
    pins.digitalWritePin(DigitalPin.P1, 1)
    music.ringTone(262)
    basic.pause(260)
    music.rest(10)
    pins.digitalWritePin(DigitalPin.P1, 0)
    servos.P2.setAngle(78)
    basic.pause(150)
    pins.digitalWritePin(DigitalPin.P1, 1)
    music.ringTone(262)
    basic.pause(260)
    music.rest(10)
    pins.digitalWritePin(DigitalPin.P1, 0)
    servos.P2.setAngle(84)
    basic.pause(150)
    pins.digitalWritePin(DigitalPin.P1, 1)
    music.ringTone(294)
    basic.pause(260)
    music.rest(10)
    pins.digitalWritePin(DigitalPin.P1, 0)
    servos.P2.setAngle(62)
    basic.pause(150)
    pins.digitalWritePin(DigitalPin.P1, 1)
    music.ringTone(196)
    basic.pause(260)
    music.rest(10)
    pins.digitalWritePin(DigitalPin.P1, 0)
    servos.P2.setAngle(90)
    basic.pause(150)
    pins.digitalWritePin(DigitalPin.P1, 1)
    music.ringTone(330)
    basic.pause(660)
    music.rest(10)
    pins.digitalWritePin(DigitalPin.P1, 0)
    servos.P2.setAngle(90)
    basic.pause(150)
    pins.digitalWritePin(DigitalPin.P1, 1)
    music.ringTone(330)
    basic.pause(260)
    music.rest(10)
    pins.digitalWritePin(DigitalPin.P1, 0)
    servos.P2.setAngle(96)
    basic.pause(150)
    pins.digitalWritePin(DigitalPin.P1, 1)
    music.ringTone(350)
    basic.pause(260)
    music.rest(10)
    pins.digitalWritePin(DigitalPin.P1, 0)
    servos.P2.setAngle(102)
    basic.pause(150)
    pins.digitalWritePin(DigitalPin.P1, 1)
    music.ringTone(392)
    basic.pause(260)
    music.rest(10)
    pins.digitalWritePin(DigitalPin.P1, 0)
    servos.P2.setAngle(96)
    basic.pause(150)
    pins.digitalWritePin(DigitalPin.P1, 1)
    music.ringTone(350)
    basic.pause(260)
    music.rest(10)
    pins.digitalWritePin(DigitalPin.P1, 0)
    servos.P2.setAngle(90)
    basic.pause(150)
    pins.digitalWritePin(DigitalPin.P1, 1)
    music.ringTone(330)
    basic.pause(260)
    music.rest(10)
    pins.digitalWritePin(DigitalPin.P1, 0)
    servos.P2.setAngle(84)
    basic.pause(150)
    pins.digitalWritePin(DigitalPin.P1, 1)
    music.ringTone(294)
    basic.pause(260)
    music.rest(10)
    pins.digitalWritePin(DigitalPin.P1, 0)
    servos.P2.setAngle(78)
    basic.pause(150)
    pins.digitalWritePin(DigitalPin.P1, 1)
    music.ringTone(262)
    basic.pause(260)
    music.rest(10)
    pins.digitalWritePin(DigitalPin.P1, 0)
    servos.P2.setAngle(78)
    basic.pause(150)
    pins.digitalWritePin(DigitalPin.P1, 1)
    music.ringTone(262)
    basic.pause(260)
    music.rest(10)
    pins.digitalWritePin(DigitalPin.P1, 0)
    servos.P2.setAngle(84)
    basic.pause(150)
    pins.digitalWritePin(DigitalPin.P1, 1)
    music.ringTone(294)
    basic.pause(260)
    music.rest(10)
    pins.digitalWritePin(DigitalPin.P1, 0)
    servos.P2.setAngle(90)
    basic.pause(150)
    pins.digitalWritePin(DigitalPin.P1, 1)
    music.ringTone(330)
    basic.pause(260)
    music.rest(10)
    pins.digitalWritePin(DigitalPin.P1, 0)
    servos.P2.setAngle(84)
    basic.pause(150)
    pins.digitalWritePin(DigitalPin.P1, 1)
    music.ringTone(294)
    basic.pause(460)
    music.rest(10)
    pins.digitalWritePin(DigitalPin.P1, 0)
    servos.P2.setAngle(78)
    basic.pause(150)
    pins.digitalWritePin(DigitalPin.P1, 1)
    music.ringTone(262)
    basic.pause(60)
    music.rest(10)
    pins.digitalWritePin(DigitalPin.P1, 0)
    servos.P2.setAngle(78)
    basic.pause(150)
    pins.digitalWritePin(DigitalPin.P1, 1)
    music.ringTone(262)
    basic.pause(260)
    music.rest(10)
    pins.digitalWritePin(DigitalPin.P1, 0)
    basic.pause(390)
    music.rest(10)
})
input.onButtonPressed(Button.B, function () {
    for (let i = 0; i <= 3 - 1; i++) {
        basic.showNumber(3 - i)
        basic.pause(250)
    }
    basic.showLeds(`
        . . . . .
        . . . . .
        . . . . .
        . . . . .
        . . . . .
        `)
    pins.digitalWritePin(DigitalPin.P1, 0)
    for (let j = 0; j <= score.length / 2 - 1; j++) {
        let tone = score[j * 2] - 1
        let duration = score[j * 2 + 1] * 100
        if (tone < 0) {
            basic.pause(duration - 10)
            music.rest(10)
        } else {
            let rad = Math.atan((tone - 9) * xstep) * 180 / Math.PI
            servos.P2.setAngle(rad + 90)
            basic.pause(150)
            pins.digitalWritePin(DigitalPin.P1, 1)
            music.ringTone(2 ** Math.floor(tone / 7) * freqs[tone % 7])
            basic.pause(duration - 140)
            music.rest(10)
            pins.digitalWritePin(DigitalPin.P1, 0)
        }
    }
    servos.P2.setAngle(90)
    music.rest(100)
})
input.onButtonPressed(Button.AB, function () {
    pins.digitalWritePin(DigitalPin.P1, 0)
    for (let k = 0; k <= 20 - 1; k++) {
        let rad = Math.atan((k - 10) * xstep) * 180 / Math.PI
        servos.P2.setAngle(rad + 90)
        basic.pause(200)
        pins.digitalWritePin(DigitalPin.P1, 1)
        basic.pause(200)
        pins.digitalWritePin(DigitalPin.P1, 0)
    }
    servos.P2.setAngle(90)
})
let xstep = 0
let tone = 0
freqs = [131, 147, 165, 175, 196, 220, 247, 262]
xstep = 0.106
score = [10, 4, 10, 4, 11, 4, 12, 4, 12, 4, 11, 4, 10, 4, 9, 4, 8, 4, 8, 4, 9, 4, 10, 4, 10, 6, 9, 2, 9, 4, -1, 4, 10, 4, 10, 4, 11, 4, 12, 4, 12, 4, 11, 4, 10, 4, 9, 4, 8, 4, 8, 4, 9, 4, 10, 4, 9, 6, 8, 2, 8, 4, -1, 4, 9, 4, 9, 4, 10, 4, 8, 4, 9, 4, 10, 2, 11, 2, 10, 4, 8, 4, 9, 4, 10, 2, 11, 2, 10, 4, 8, 4, 8, 4, 9, 4, 5, 4, 10, 8, 10, 4, 11, 4, 12, 4, 11, 4, 10, 4, 9, 4, 8, 4, 8, 4, 9, 4, 10, 4, 9, 6, 8, 2, 8, 4, -1, 4]
pins.digitalWritePin(DigitalPin.P1, laser)
// basic.showNumber(score.length)
servos.P2.setAngle(90)
basic.forever(function () {

})
